### ISSUE TITLE
How to install a new version?

### ISSUE THREAD

**Issue by mikaaax** [ts1/flipbook-vue#70]
Hello. I cannt install a new version, I dont know why. Can you help me? My test page is here https://gryfnekadry.pl/grand3/public/ ...

**Comment by ts1** [comment]
Your page has flipbook-vue built into `app.js` and it is being used, so the `<script>` tag that loads from unpkg.com is not being used.
You will need to work on the source, npm update etc. to update flipbook-vue and re-build it.
This is a general JS development topic and has nothing to do with flipbook-vue itself, so this issue is closed.
